print("Hola Carlos, como estas")
print("Hola Juan, bien y tu")
print("Cual es tu comoida favorita Carlos")
print("Pollo frito, y la tuya")
print("mole con pollo")
print("De donde eres Juan")
print("Mexico y tu Juan")
print("Soy de Colombia")